[package]
name = "multisig-ism"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh = "0.9"
num-derive = "0.3"
num-traits = "0.2"
solana-program = "=1.14.13"
hyperlane-core = { path = "../hyperlane-core" }
# hyperlane-sealevel-mailbox = { path = "../../mailbox", features = ["no-entrypoint"] }
thiserror = "1.0"

[dev-dependencies]
hex = "0.4.3"

[lib]
crate-type = ["cdylib", "lib"]
