[workspace]
members = [
    "hyperlane-core",
    "client",
    "multisig-ism",
    "programs/mailbox",
    "programs/recipient/echo",
    "programs/ism/rubber-stamp",
    "programs/ism/multisig-ism-message-id",
    "programs/hyperlane-sealevel-token",
]
