[package]
name = "HyperlaneLibrary"
version = "1.0.0"
authors = []

[addresses]
hp_library = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
