[package]
name = "hyperlane-sealevel-multisig-ism-message-id"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh = "0.9"
multisig-ism = { path = "../../../libraries/multisig-ism" }
num-derive = "0.3"
num-traits = "0.2"
solana-program = "=1.14.13"
access-control = { path = "../../../libraries/access-control" }
hyperlane-core = { path = "../../../hyperlane-core" }
hyperlane-sealevel-mailbox = { path = "../../mailbox", features = ["no-entrypoint"] }
hyperlane-sealevel-interchain-security-module-interface = { path = "../../../libraries/interchain-security-module-interface" }
serializable-account-meta = { path = "../../../libraries/serializable-account-meta" }
thiserror = "1.0"

[dev-dependencies]
solana-program-test = "=1.14.13"
solana-sdk = "=1.14.13"
hex = "0.4.3"
multisig-ism = { path = "../../../libraries/multisig-ism", features = ["test-data"] }

[lib]
crate-type = ["cdylib", "lib"]
