cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-sealevel-multisig-ism-message-id"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
num-derive.workspace = true
num-traits.workspace = true
solana-program.workspace = true
thiserror.workspace = true

access-control = { path = "../../../libraries/access-control" }
account-utils = { path = "../../../libraries/account-utils" }
ecdsa-signature = { path = "../../../libraries/ecdsa-signature" }
hyperlane-core = { path = "../../../../hyperlane-core" }
hyperlane-sealevel-interchain-security-module-interface = { path = "../../../libraries/interchain-security-module-interface" }
hyperlane-sealevel-mailbox = { path = "../../mailbox", features = ["no-entrypoint"] }
multisig-ism = { path = "../../../libraries/multisig-ism" }
serializable-account-meta = { path = "../../../libraries/serializable-account-meta" }

[dev-dependencies]
hex.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
