apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent-common.fullname" . }}
  labels:
    {{- include "agent-common.labels" . | nindent 4 }}
data:
  ONELINE_BACKTRACES: "true"
  RUST_BACKTRACE: {{ .Values.hyperlane.rustBacktrace }}
  HYP_db: {{ .Values.hyperlane.dbPath }}
  HYP_log_format: {{ .Values.hyperlane.tracing.format }}
  HYP_log_level: {{ .Values.hyperlane.tracing.level }}
  {{- range .Values.hyperlane.chains }}
{{- include "agent-common.config-env-vars" (dict "config" . "key_name_prefix" (printf "chains_%s_" .name) "format" "config_map") | indent 2 }}
  {{- end }}
  HYP_metricsPort: {{ .Values.hyperlane.metrics.port | quote }}
