name: 'Yarn Build with Cache'
description: 'Run yarn build using yarn cache'

inputs:
  ref:
    description: 'The Git ref to checkout'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        submodules: recursive
        fetch-depth: 0

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          **/node_modules
          .yarn
        key: ${{ runner.os }}-yarn-cache-${{ hashFiles('./yarn.lock') }}
        fail-on-cache-miss: true

    - name: Build
      shell: bash
      run: yarn build
