[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
sea-orm-migration = { version = "0.9", features = ["runtime-tokio-native-tls", "sqlx-postgres"]}
serde = { version = "1.0", features = ["derive"] }
abacus-core = { path = "../../../abacus-core" }

[dependencies.sea-orm]
features = ["macros"]

[[bin]]
name = "init-db"
path = "bin/init_db.rs"
