[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
hyperlane-core = { path = "../../../hyperlane-core" }
sea-orm = {version = "0.11", features = ["macros", "with-bigdecimal", "with-time"], default-features = false}
sea-orm-migration = { version = "0.11", features = ["runtime-tokio-native-tls", "sqlx-postgres"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["rt", "macros"] }
time = "0.3"

# bin-only deps
tracing-subscriber = { version = "0.3" }
tracing = { version = "0.1", features = ["release_max_level_debug"] }

[[bin]]
name = "init-db"
path = "bin/init_db.rs"

[[bin]]
name = "recreate-db"
path = "bin/recreate_db.rs"

[[bin]]
name = "generate-entities"
path = "bin/generate_entities.rs"

[features]
default = []
