[package]
name = "hyperlane-sealevel-ism-rubber-stamp"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh = "0.9"
solana-program = "=1.14.13"
hyperlane-core = { path = "../../../hyperlane-core" }
hyperlane-sealevel-interchain-security-module-interface = { path = "../../../libraries/interchain-security-module-interface" }

[lib]
crate-type = ["cdylib", "lib"]
