[package]
name = "hyperlane-sealevel-test-ism"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
account-utils = { path = "../../../libraries/account-utils" }
borsh = "0.9"
solana-program = "=1.14.13"
serializable-account-meta = { path = "../../../libraries/serializable-account-meta" }
hyperlane-core = { path = "../../../hyperlane-core" }
hyperlane-sealevel-mailbox = { path = "../../mailbox", features = ["no-entrypoint"] }
hyperlane-sealevel-interchain-security-module-interface = { path = "../../../libraries/interchain-security-module-interface" }

[lib]
crate-type = ["cdylib", "lib"]
