[package]
name = "hyperlane-sealevel-test-ism"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
test-client = ["dep:solana-program-test", "dep:solana-sdk", "dep:hyperlane-test-utils"]

[dependencies]
account-utils = { path = "../../../libraries/account-utils" }
borsh = "0.9"
solana-program = "=1.14.13"
serializable-account-meta = { path = "../../../libraries/serializable-account-meta" }
hyperlane-core = { path = "../../../hyperlane-core" }
hyperlane-sealevel-mailbox = { path = "../../mailbox", features = ["no-entrypoint"] }
hyperlane-sealevel-interchain-security-module-interface = { path = "../../../libraries/interchain-security-module-interface" }

solana-program-test = { version = "=1.14.13", optional = true }
solana-sdk = { version = "=1.14.13", optional = true }
hyperlane-test-utils = { path = "../../../libraries/test-utils", optional = true }

[lib]
crate-type = ["cdylib", "lib"]
