[package]
name = "access-control"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "=1.14.13"

[dev-dependencies]
solana-program-test = "=1.14.13"
solana-sdk = "=1.14.13"

[lib]
crate-type = ["cdylib", "lib"]
