[package]
name = "hyperlane-sealevel-mailbox"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
hyperlane-core = { path = "../../hyperlane-core" }
borsh = "0.9"
num-derive = "0.3"
num-traits = "0.2"
solana-program = "=1.14.13"
thiserror = "1.0"
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }
hyperlane-sealevel-message-recipient-interface = { path = "../../libraries/message-recipient-interface" }
hyperlane-sealevel-interchain-security-module-interface = { path = "../../libraries/interchain-security-module-interface" }

bs58 = "=0.4.0" # FIXME remove

[dependencies.spl-noop]
version = "=0.1.3"
features = ["no-entrypoint"]
git = "https://github.com/tkporter/eclipse-program-library"
branch = "trevor/steven/eclipse-1.14.13/with-tlv-lib"

[dev-dependencies]
base64 = "0.13"
itertools =  "0.10.1"
log = "0.4"
testing_logger = "=0.1.1"

[lib]
crate-type = ["cdylib", "lib"]
