[package]
name = "hyperlane-sealevel-client"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9"
clap = { version = "4", features = ["derive"] }
hyperlane-sealevel-ism-rubber-stamp = { path = "../programs/ism/rubber-stamp" }
hyperlane-sealevel-mailbox = { path = "../programs/mailbox" }
hyperlane-sealevel-recipient-echo = { path = "../programs/recipient/echo" }
hyperlane-sealevel-token = { path = "../programs/hyperlane-sealevel-token" }
hyperlane-sealevel-token-native = { path = "../programs/hyperlane-sealevel-token-native" }
hyperlane-sealevel-token-lib = { path = "../libraries/hyperlane-sealevel-token" }
hyperlane-sealevel-connection-client = { path = "../libraries/hyperlane-sealevel-connection-client" }
lazy_static = "1.4"
pretty_env_logger = "0.4"
solana-client = "=1.14.13"
solana-cli-config = "=1.14.13"
solana-clap-utils = "=1.14.13"
solana-program = "=1.14.13"
solana-sdk = "=1.14.13"
