cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-sealevel-igp"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
no-spl-noop = []

[dependencies]
hyperlane-core = { path = "../../../hyperlane-core" }
access-control = { path = "../../libraries/access-control" }
account-utils = { path = "../../libraries/account-utils" }
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }
borsh.workspace = true
solana-program.workspace = true
num-derive.workspace = true
num-traits.workspace = true
thiserror.workspace = true
getrandom.workspace = true

[dev-dependencies]
solana-program-test.workspace = true
solana-sdk.workspace = true
hyperlane-test-utils ={ path = "../../libraries/test-utils" }

[lib]
crate-type = ["cdylib", "lib"]
