[package]
name = "hyperlane-test-transaction-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.14.13"
solana-program-test = "=1.14.13"
solana-sdk = "=1.14.13"

[lib]
crate-type = ["cdylib", "lib"]
