cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-sealevel-validator-announce"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
solana-program.workspace = true
thiserror.workspace = true

account-utils = { path = "../../libraries/account-utils" }
ecdsa-signature = { path = "../../libraries/ecdsa-signature" }
hyperlane-sealevel-mailbox = { path = "../mailbox", features = ["no-entrypoint"] }
hyperlane-core = { path = "../../../hyperlane-core" }
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }

# Required to allow dependencies `getrandom` but to preserve determinism required by programs, see
# https://github.com/solana-labs/solana/blob/master/docs/src/developing/on-chain-programs/developing-rust.md#depending-on-rand
getrandom = { version = "0.2", features = ["custom"] }

[dev-dependencies]
hex.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
