[package]
name = "multisig-ism"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
test-data = ["dep:hex"]

[dependencies]
borsh = "0.9"
ecdsa-signature = { path = "../ecdsa-signature" }
solana-program = "=1.14.13"
hyperlane-core = { path = "../../hyperlane-core" }
thiserror = "1.0"
hex = { version = "0.4.3", optional = true }

[dependencies.spl-type-length-value]
version = "0.1.0"
git = "https://github.com/tkporter/eclipse-program-library"
branch = "trevor/steven/eclipse-1.14.13/with-tlv-lib"
features = ["borsh"]

[dev-dependencies]
hex = "0.4.3"

[lib]
crate-type = ["cdylib", "lib"]
