cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-application"
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license-file = { workspace = true }
publish = { workspace = true }
version = { workspace = true }

[dependencies]
hyperlane-core = { path = "../../hyperlane-core" }

async-trait.workspace = true
thiserror.workspace = true
