apiVersion: batch/v1
kind: CronJob
metadata:
  name: relayer-funder
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: relayer-funder
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - ./node_modules/.bin/ts-node
            - ./typescript/infra/scripts/funding/fund-relayers-from-deployer.ts
            - -e
            - {{ .Values.abacus.runEnv }}
            - --context
            - {{ .Values.abacus.contextFundingFrom }}
{{- range .Values.abacus.rolesToFund }}
            - --roles-to-fund
            - {{ . }}
{{- end }}
{{- range .Values.abacus.contextsToFund }}
            - -f
            - /addresses-secret/{{ . }}-addresses.json
{{- end }}
            env:
            - name: PROMETHEUS_PUSH_GATEWAY
              value: {{ .Values.infra.prometheusPushGateway }}
            envFrom:
            - secretRef:
                name: relayer-funder-env-var-secret
            volumeMounts:
            - name: relayer-funder-addresses-secret
              mountPath: /addresses-secret
          volumes:
          - name: relayer-funder-addresses-secret
            secret:
              secretName: relayer-funder-addresses-secret
              defaultMode: 0400
