name: node

on:
  # Triggers the workflow on push or pull request against main
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEBUG: 'hyperlane:*'

jobs:
  yarn-install:
    runs-on: larger-runner
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('./yarn.lock') }}

      - name: yarn-install
        run: |
          yarn install
          CHANGES=$(git status -s --ignore-submodules)
          if [[ ! -z $CHANGES ]]; then
            echo "Changes found: $CHANGES"
            git diff
            exit 1
          fi

  yarn-build:
    runs-on: larger-runner
    needs: [yarn-install]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('./yarn.lock') }}

      - name: build-cache
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: build
        run: yarn build

  lint-prettier:
    runs-on: larger-runner
    needs: [yarn-install]
    steps:
      - uses: actions/checkout@v3
        with:
          # check out full history
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('./yarn.lock') }}

      - name: lint
        run: yarn lint

      - name: prettier
        run: |
          yarn prettier
          CHANGES=$(git status -s)
          if [[ ! -z $CHANGES ]]; then
            echo "Changes found: $CHANGES"
            exit 1
          fi

  test:
    runs-on: larger-runner
    needs: [yarn-build]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1

      - uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Unit Tests
        run: yarn test

  test-cli:
    runs-on: larger-runner
    needs: [yarn-build]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1

      - uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: test
        run: ./typescript/cli/ci-test.sh

  test-env:
    runs-on: larger-runner
    needs: [yarn-build]
    strategy:
      matrix:
        environment: [testnet4, mainnet3]
        module: [ism, core, helloworld]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1

      - name: Test ${{ matrix.environment }} ${{ matrix.module }} deployment (check, deploy, govern, check again)
        run: cd typescript/infra && ./fork.sh ${{ matrix.environment }} ${{ matrix.module }}

  coverage:
    runs-on: larger-runner
    needs: [yarn-build]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('./yarn.lock') }}

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1

      - name: Run tests with coverage
        run: yarn coverage
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
