name: Build and Push Agent Image
on:
  push:
    branches: [main]
    tags:
      - '**'
  pull_request:
    paths:
      - 'rust/**'
      - '.github/workflows/rust-docker.yml'
  workflow_dispatch:
  

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: raas-abc-hyperlane-monorepo


concurrency:
  group: build-push-agents-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build-and-push-to-gcr:
    runs-on: buildjet-8vcpu-ubuntu-2204

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Generate tag data
        id: taggen
        run: |
          echo "TAG_DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
          echo "TAG_SHA=$(echo '${{ github.event.pull_request.head.sha || github.sha }}' | cut -b 1-7)" >> $GITHUB_OUTPUT
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/gelatodigital/raas-abc-hyperlane-monorepo
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=${{ steps.taggen.outputs.TAG_SHA }}-${{ steps.taggen.outputs.TAG_DATE }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./rust/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
